language: go
go:
  - 1.8.1
install:
  - docker-compose up -d
  - go get -u github.com/Masterminds/glide
  - glide install
script:
  - go test $(glide novendor)
  - docker-compose down
sudo: required
services:
  - docker
notifications:
  email: false
