language: go
go:
  - 1.5.4
  - 1.6.3
install:
  - go get github.com/coreos/etcd
  - go get -t -v ./...
  - go build -v ./...
script:
  - etcd &
  - go test -v ./...
  - kill %1
sudo: false
notifications:
  email: false
